import { NapProtoMsg, ProtoField, ScalarType } from '@napneko/nap-proto-core';
import { PbReserve1 } from '@/core/packet/message/PbReserve';

export const CustomFaceElement = new NapProtoMsg({
    guid: ProtoField(1, ScalarType.BYTES, true, false),
    filePath: ProtoField(2, ScalarType.STRING, true, false),
    shortcut: ProtoField(3, ScalarType.STRING, true, false),
    buffer: ProtoField(4, ScalarType.BYTES, true, false),
    flag: ProtoField(5, ScalarType.BYTES, true, false),
    oldData: ProtoField(6, ScalarType.BYTES, true, false),
    fileId: ProtoField(7, ScalarType.UINT32, false, false),
    serverIp: ProtoField(8, ScalarType.INT32, true, false),
    serverPort: ProtoField(9, ScalarType.INT32, true, false),
    fileType: ProtoField(10, ScalarType.INT32, false, false),
    signature: ProtoField(11, ScalarType.BYTES, true, false),
    useful: ProtoField(12, ScalarType.INT32, false, false),
    md5: ProtoField(13, ScalarType.BYTES, true, false),
    thumbUrl: ProtoField(14, ScalarType.STRING, true, false),
    bigUrl: ProtoField(15, ScalarType.STRING, true, false),
    origUrl: ProtoField(16, ScalarType.STRING, true, false),
    bizType: ProtoField(17, ScalarType.INT32, false, false),
    repeatIndex: ProtoField(18, ScalarType.INT32, false, false),
    repeatImage: ProtoField(19, ScalarType.INT32, false, false),
    imageType: ProtoField(20, ScalarType.INT32, false, false),
    index: ProtoField(21, ScalarType.INT32, false, false),
    width: ProtoField(22, ScalarType.INT32, false, false),
    height: ProtoField(23, ScalarType.INT32, false, false),
    source: ProtoField(24, ScalarType.INT32, false, false),
    size: ProtoField(25, ScalarType.UINT32, false, false),
    origin: ProtoField(26, ScalarType.INT32, false, false),
    thumbWidth: ProtoField(27, ScalarType.INT32, true, false),
    thumbHeight: ProtoField(28, ScalarType.INT32, true, false),
    showLen: ProtoField(29, ScalarType.INT32, false, false),
    downloadLen: ProtoField(30, ScalarType.INT32, false, false),
    x400Url: ProtoField(31, ScalarType.STRING, true, false),
    x400Width: ProtoField(32, ScalarType.INT32, false, false),
    x400Height: ProtoField(33, ScalarType.INT32, false, false),
    pbReserve: ProtoField(34, () => PbReserve1.fields, true, false),
});